title: Title
author: wryyyyyyyyyyyyyyyyyyyy-afk
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Description YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  wryyyyyyyyyyyyyyyyyyyy-afk # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-slate
